-- =============================================
-- SCRIPT PARA DROPAR TUDO
-- CUIDADO: Este script remove TODAS as tabelas e dados
-- =============================================

-- DESABILITAR TODAS AS POLÍTICAS RLS PRIMEIRO
ALTER TABLE IF EXISTS cargas_exercicio DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS feedback_treino DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS execucoes_treino DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS treinos_atribuidos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS exames_documentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS profissional_cliente DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS profissionais DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_streaks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS insights DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS treinos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS dores DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;

-- DROPAR TABELAS DO SISTEMA PROFISSIONAL (na ordem correta)
DROP TABLE IF EXISTS cargas_exercicio CASCADE;
DROP TABLE IF EXISTS feedback_treino CASCADE;
DROP TABLE IF EXISTS execucoes_treino CASCADE;
DROP TABLE IF EXISTS treinos_atribuidos CASCADE;
DROP TABLE IF EXISTS exames_documentos CASCADE;
DROP TABLE IF EXISTS profissional_cliente CASCADE;
DROP TABLE IF EXISTS profissionais CASCADE;
DROP TABLE IF EXISTS avaliacoes_profissionais CASCADE;
DROP TABLE IF EXISTS mensagens_profissional CASCADE;
DROP TABLE IF EXISTS planos_tratamento CASCADE;

-- DROPAR TABELAS BÁSICAS
DROP TABLE IF EXISTS user_streaks CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;
DROP TABLE IF EXISTS insights CASCADE;
DROP TABLE IF EXISTS treinos CASCADE;
DROP TABLE IF EXISTS dores CASCADE;

-- DROPAR TABELAS DE SISTEMA EXISTENTES
DROP TABLE IF EXISTS treinos_logs CASCADE;
DROP TABLE IF EXISTS dores_logs CASCADE;
DROP TABLE IF EXISTS personal_aluno CASCADE;
DROP TABLE IF EXISTS comunidade_posts CASCADE;
DROP TABLE IF EXISTS comunidade_comentarios CASCADE;
DROP TABLE IF EXISTS pagamentos CASCADE;

-- DROPAR USUÁRIOS POR ÚLTIMO
DROP TABLE IF EXISTS users CASCADE;

-- DROPAR VIEWS SE EXISTIREM
DROP VIEW IF EXISTS view_profissionais_completa;
DROP VIEW IF EXISTS view_cliente_dashboard;

-- DROPAR FUNÇÕES
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;

-- DROPAR STORAGE BUCKET (comentado por segurança)
-- DELETE FROM storage.objects WHERE bucket_id = 'medical-documents';
-- DELETE FROM storage.buckets WHERE id = 'medical-documents';

-- VERIFICAR O QUE SOBROU
SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename;